#!/usr/bin/env node
/**
 * generate-env.js
 *
 * Vercel pre-build script: generates src/environments/environment.prod.ts
 * from Vercel Environment Variables — no secrets ever committed to the repo.
 *
 * Required Vercel Environment Variables:
 *   - NG_API_URL: Target backend API URL (e.g. http://localhost:3000 or your deployed backend URL)
 *
 * Run as: node scripts/generate-env.js
 */

const fs = require('fs');
const path = require('path');

const apiUrl = process.env.NG_API_URL;

if (!apiUrl) {
  console.error('[generate-env] ERROR: NG_API_URL environment variable is not set.');
  console.error('[generate-env] Set it in Vercel project settings → Environment Variables.');
  process.exit(1);
}

const content = `// AUTO-GENERATED by scripts/generate-env.js — do not edit manually.
// This file is produced at build time from Vercel environment variables.
export const environment = {
  production: true,
  apiUrl: '${apiUrl}'
};
`;

const envDir = path.join(__dirname, '..', 'src', 'environments');
const envFile = path.join(envDir, 'environment.prod.ts');

// Also write environment.ts so tsc can resolve the import during build
const envDevFile = path.join(envDir, 'environment.ts');

if (!fs.existsSync(envDir)) {
  fs.mkdirSync(envDir, { recursive: true });
}

fs.writeFileSync(envFile, content, 'utf8');
fs.writeFileSync(envDevFile, content, 'utf8');

console.log(`[generate-env] ✅ Generated environment files successfully`);
